### PR TITLE
Delete refresh

### PR DESCRIPTION
**Pull request by katjam**
2 tests have been disabled - others USUALLY pass

### CODE REVIEW

**Comment by katjam** [comment]
@tomltd ignore the tests - please merge so @jermyk can start testing this functionality https://trello.com/c/MdM7A1oN/395-m-cached-back-button-but-no-back-navigation-does-not-seem-correct-clear-cache-on-delete

**Comment by tomltd** [comment]
Yarrrgh she's still broken

**Comment by katjam** [comment]
works on my local - but I think I might start from scratch with these!

**Comment by tomltd** [comment]
:shipit: is :panda_face: :+1: :cactus:

**Pull request merged**
