### PR TITLE
Delete refresh

### PR DESCRIPTION
**Pull request by katjam**
@tomltd See what you think and run on ESA for a bit. If it is sounds, I'll port to PIP.

### CODE REVIEW

**Comment by katjam** [comment]
@tomltd I will get the build/ tests working first though... no worries on the merge front yet.

**Comment by tomltd** [comment]
Ok dokie :cactus:

**Comment by katjam** [comment]
cactus!

**Comment by tomltd** [comment]
I was looking for :chicken: fajitas but no luck

**Pull request closed without merging**
