### PR TITLE
qualify card wording consistent

### PR DESCRIPTION
**Pull request by katjam**

### CODE REVIEW

**Comment by tomltd** [comment]
:+1: :hamburger: :hammer: :hamster:

**Comment by katjam** [comment]
Not working ;)

**Comment by tomltd** [comment]
Whoops I'll stay out of it unless you assign me :-1:

**Comment by katjam** [comment]
No I meant - 'I am not working' - like pretending I am not working - like
you should be.

**Comment by tomltd** [comment]
I realised that after I commented but then I didn't fix it because I'm not working :construction_worker:

**Comment by katjam** [comment]
Oh good. Me neither. Just finished!

**Comment by harryharrold** [comment]
Well, I'm glad neither of you are working on your days off.

**Pull request merged**
