### PR TITLE
Remove old link to survey and add popup code

### PR DESCRIPTION
**Pull request by katjam**

### CODE REVIEW

**Review by tomltd — COMMENTED** [review]
:shipit: 👍  💯  🎱  🍶  👓 

:neckbeard: 🚶 

🗡  💃  🐡

**Review by tomltd — APPROVED** [review]

**Comment by katjam** [comment]
I think we'll have to change it though. Because it's a one page app - the
survey pops up when you first visit the site.

We'll want to find a good trigger for it to popup when the user gets to a
certain point in the app - or make a link like before.

**Review by tomltd — APPROVED** [review]
👍  :shipit:

**Review by tomltd — APPROVED** [review]
👍  💅

**Pull request merged**
